//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Socios
    {
        public int IdSocio { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public long Cedula { get; set; }
        public string Foto { get; set; }
        public string Direccion { get; set; }
        public long Telefono { get; set; }
        public string Sexo { get; set; }
        public int Edad { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int Afiliados { get; set; }
        public int Tipo_Membresia { get; set; }
        public string LugarTrabajo { get; set; }
        public string DireccionOficina { get; set; }
        public long TelOficiona { get; set; }
        public int EstadoMembrecia { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
    
        public virtual Afiliados Afiliados1 { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual MemberShip MemberShip { get; set; }
    }
}
